# project purpose and definition documentation

[REQ-1]
text = '''
# Forward
These are a set of requirements, specifications and tests for raising children
from birth to the age of 18.  I am writing these mostly because I think it is
funny to write such design documents and the idea we can have ANY "design" on
our children is a humourous thought.

That asside, I will try to write in as serious a style as possible, mostly because
being "serious" makes this even more commical.

# Design Documents for Raising Children
In order to properly document how children should be raised, we shall first define
a set of high level requirements which all other requirements and specifications
will implement.

The primary requirements for a child who turns 18 are outlined below. We use this
as our top level requirements because they will help guide how we define our
specifications (how we will actually be a parent):
- [[REQ-safe]]: the risk of serious injury and/or death should be prevented.
- [[REQ-healthy]]: the child should develop healthy habbits including diet,
  exercise and meditation.
- [[REQ-dependency]]: the child should learn the value and costs of both
  dependency and independence and be able to apply them wisely.
- [[REQ-wisdom]]: the child should be on a path of wisdom and be able to make
  choices that are as fair and impartial as possible.
- [[REQ-moral]]: the child should have moral character.
'''
